title: memory-match
name: Fantastic Memory Match
description: This is a simple memory match web game built with vanilla JavaScript, HTML5, and CSS3.
company: Cyberdime Development
author: John Norris
email: info@cyberdime.com
github: https://github.com/cyberdime-dev
linkedin: https://www.linkedin.com/in/cyberdime-dev
